# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Projet/Vivado/Custom_IP/Vivado_17.2/Zybo_target/Zybo_test/Zybo_test.srcs/sources_1/bd/Test/ip/Test_auto_pc_0/Test_auto_pc_0.xci
# IP: The module: 'Test_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projet/Vivado/Custom_IP/Vivado_17.2/Zybo_target/Zybo_test/Zybo_test.srcs/sources_1/bd/Test/ip/Test_auto_pc_0/Test_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Projet/Vivado/Custom_IP/Vivado_17.2/Zybo_target/Zybo_test/Zybo_test.srcs/sources_1/bd/Test/ip/Test_auto_pc_0/Test_auto_pc_0.xci
# IP: The module: 'Test_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projet/Vivado/Custom_IP/Vivado_17.2/Zybo_target/Zybo_test/Zybo_test.srcs/sources_1/bd/Test/ip/Test_auto_pc_0/Test_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
