# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/test_xdc.xdc

# Block Designs: bd/Test/Test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test || ORIG_REF_NAME==Test}]

# IP: bd/Test/ip/Test_processing_system7_0_0/Test_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_processing_system7_0_0 || ORIG_REF_NAME==Test_processing_system7_0_0}]

# IP: bd/Test/ip/Test_axi_gpio_0_0/Test_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_axi_gpio_0_0 || ORIG_REF_NAME==Test_axi_gpio_0_0}]

# IP: bd/Test/ip/Test_ps7_0_axi_periph_0/Test_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_ps7_0_axi_periph_0 || ORIG_REF_NAME==Test_ps7_0_axi_periph_0}]

# IP: bd/Test/ip/Test_rst_ps7_0_100M_0/Test_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_rst_ps7_0_100M_0 || ORIG_REF_NAME==Test_rst_ps7_0_100M_0}]

# IP: bd/Test/ip/Test_xbar_0/Test_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_xbar_0 || ORIG_REF_NAME==Test_xbar_0}]

# IP: bd/Test/ip/Test_Motor_0_1/Test_Motor_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_Motor_0_1 || ORIG_REF_NAME==Test_Motor_0_1}]

# IP: bd/Test/ip/Test_Encoder_0_0/Test_Encoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_Encoder_0_0 || ORIG_REF_NAME==Test_Encoder_0_0}]

# IP: bd/Test/ip/Test_Derivator_0_0/Test_Derivator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_Derivator_0_0 || ORIG_REF_NAME==Test_Derivator_0_0}]

# IP: bd/Test/ip/Test_PID_0_0/Test_PID_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_PID_0_0 || ORIG_REF_NAME==Test_PID_0_0}]

# IP: bd/Test/ip/Test_Subtractor_0_0/Test_Subtractor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_Subtractor_0_0 || ORIG_REF_NAME==Test_Subtractor_0_0}]

# IP: bd/Test/ip/Test_Odometer_0_0/Test_Odometer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_Odometer_0_0 || ORIG_REF_NAME==Test_Odometer_0_0}]

# IP: bd/Test/ip/Test_auto_pc_0/Test_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_auto_pc_0 || ORIG_REF_NAME==Test_auto_pc_0}]

# XDC: bd/Test/Test_ooc.xdc
